#!/bin/bash

acc new abc088
mv abc088/contest.acc.json ./

jq -r '.tasks[].id' ./contest.acc.json | while read tid; do
  mv abc088/${tid: -1} app/
  ./setting ${tid: -1}
done

rmdir abc088
cp contest.acc.json app/
ln -s ./app ./abc088

./resetting a
