#!/bin/bash

stack exec -- add-entry $1

echo "export CURRENT_STACK_EXE_ENTRY=$1" > .curname

stack build abc086:exe:$1

if type "gen-hie" > /dev/null 2>&1; then
  gen-hie > hie.yaml
else
  stack install implicit-hie
  gen-hie > hie.yaml
fi
