#!/bin/bash

acc new abc083
mv abc083/contest.acc.json ./

jq -r '.tasks[].id' ./contest.acc.json | while read tid; do
  mv abc083/${tid: -1} app/
  ./setting ${tid: -1}
done

rmdir abc083
cp contest.acc.json app/
ln -s ./app ./abc083

./resetting a
