#!/bin/bash

acc new abc085
mv abc085/contest.acc.json ./

jq -r '.tasks[].id' ./contest.acc.json | while read tid; do
  mv abc085/${tid: -1} app/
  ./setting ${tid: -1}
done

rmdir abc085
cp contest.acc.json app/
ln -s ./app ./abc085

./resetting a
